=== FilipeVilela280/tcm23twg02/Html/library_XSD.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.library.org"
    xmlns:tns="http://www.library.org"
    elementFormDefault="qualified">
   
    <element name="library">
        <complexType>
            <sequence>
                <element name="Produto" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="nome" type="string" />
                            <element name="imagem"  >
                                <simpleType>
                                    <restriction base="string">
                                        <pattern
                                            value="imagens\/[a-zA-Z0-9_-]+\.jpg"></pattern>
                                    </restriction>
                                </simpleType>
                            </element>
 
                            <element name="descrição" type="string"/>
                            <element name="preco" >
                                <simpleType>
                                    <restriction base="string">
                                        <pattern
                                            value="\d+€"></pattern>
                                    </restriction>
                                </simpleType>
                            </element>

                            
                            <element name="vídeo" type="string"/>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>

</schema>

=== FilipeVilela280/tcm23twg02/Html/library_Smartphones.xml
<?xml version="1.0"?>
<library xmlns="http://www.library.org"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.library.org library_XSD.xsd" >
	<Produto >
		<nome>Xiaomi Redmi Note 12 4G 4GB/128GB Dual SIM Ice Blue</nome>
		<imagem>imagens/redminote12.jpg</imagem>
		<descrição>    Processador Octa-Core Snapdragon 685
         Ecrã de 6.67" FHD+ AMOLED
          Taxa de atualização de 120 Hz
        Bateria de 5000mAh </descrição>
		 <preco>189€</preco>
		 <vídeo>https://youtu.be/T1g0qiQ4aVk?si=yAYpNPVS8O7U_ZCb</vídeo>
	</Produto>
	
	<Produto >
		
		<nome>Xiaomi 13T 6.67" 12GB/256GB Dual SIM Alpine</nome>
		<imagem>imagens/xiaomi13t.jpg</imagem>
		<descrição>     Processador: Octa-core  
        Gráfica: Mali-G610
        Armazenamento: 256GB 
       Memória RAM: 12GB</descrição>
		 <preco>699€</preco>
		 <vídeo>https://youtu.be/YJLpV6u5G4w?si=q_RJvO6YwMjlWyd_</vídeo>
	</Produto>
	
	
	<Produto >
	
		<nome>Apple iPhone 14 6.1" 128GB</nome>
		<imagem>imagens/iphone14.jpg</imagem>
		<descrição>    Processador A15 Bionic
        Nova CPU 6core 
        Ecrã Super Retina XDR de 6.1 polegadas</descrição>
		 <preco>869€</preco>
		 <vídeo>https://youtu.be/Ht90J5MwpUg?si=ySdwoFwBFlGZ27rV</vídeo>
	</Produto>
	
	
	<Produto >
		<nome>Xiaomi Poco X5 5G 6.6" 8GB/256GB Dual SIM</nome>
		<imagem>imagens/xiaomipocox5.jpg</imagem>
		<descrição>Processador Snapdragon® 695 com processo avançado de 6 nm
        Ecrã AMOLED FHD+ de 120 Hz </descrição>
		 <preco>390€</preco>
		 <vídeo>https://youtu.be/MOqaYHZZVkI?si=P03EPdRaX1vOctuM</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Xiaomi Poco F4 GT 6.67" 12GB/256GB Dual SIM </nome>
		<imagem>imagens/xiaomipocof4.jpg</imagem>
		<descrição>   Processador Flagship 4nm Snapdragon® 8 Gen 1 
        Carregamento HyperCharge Smart 120W;
       Tecnologia Multi-Link 5.0;
        </descrição>
		 <preco>449€</preco>
		 <vídeo>https://youtu.be/713Xmj1jlVg?si=7nRNKDKQybZPb5ET</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Oneplus Nord CE 3 Lite 5G 6.72" 8GB/128GB </nome>
		<imagem>imagens/OneplusNord.jpg</imagem>
		<descrição>Sistema de Câmara 108 MP
       Expansão da RAM Virtual de 8GB
       Grande ecrã de 17.07cm (6.72") 120 Hz</descrição>
		 <preco>299€</preco>
		 <vídeo>https://youtu.be/-ljUiXk0Ak0?si=KWHgMGilTEn_akXo</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Nothing Phone 6.7" 12GB/512GB Dual SIM Branco</nome>
		<imagem>imagens/nothingphine.jpg</imagem>
		<descrição>
          Processador Snapdragon® 8+ Gen 1  
           Ecrã 120Hz de 6.7" com painel OLED;
          Dupla câmara traseira de 50MP com sensor Sony e Samsung;</descrição>
		 <preco>699€</preco>
		 <vídeo>https://youtu.be/Jb88eui8SqQ?si=hM0YLnXOaJyxlbS9</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Samsung Galaxy S23 FE  8GB/128GB </nome>
		<imagem>imagens/glaxys23.jpg</imagem>
		<descrição>     Octa-core 
        Dynamic AMOLED 2X 120Hz
       Dynamic AMOLED 2X, 120Hz 
       50 MP, f/1.8, 24mm </descrição>
		 <preco>739€</preco>
		 <vídeo>https://youtu.be/XaDU2xJT9pg?si=1o1VB42NiivzfQUU</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Vivo Y21s 6.51" 4GB/128GB Dual SIM</nome>
		<imagem>imagens/vivoy21s.jpg</imagem>
		<descrição>Câmara principal de 50 MP 
          Bateria de 5000 mAh + Carga Rápida de 18W
        Design fino e elegante com 8 mm de espessura</descrição>
		 <preco>209€</preco>
		 <vídeo>https://youtu.be/5dDI2yI2y_8?si=88xJ34fgkvU0QgJF</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Smartphone Samsung Galaxy Z Fold 5 7.6" 12GB/512GB</nome>
		<imagem>imagens/samsunggalaxyz.jpg</imagem>
		<descrição>Potente CPU Snapdragon 8 Gen 2
      Ecrã interior de 7.6" 
      Ecrã exterior de 6.2" Dynamic 
     Experiência fotográfica de topo</descrição>
		 <preco>1899€</preco>
		 <vídeo>https://youtu.be/VjN-FmXPUFU?si=PlbgKIyEnXNw3KpC</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Blackview A100 6.6" 6GB/128GB Dual SIM </nome>
		<imagem>imagens/blackviewa100.jpg</imagem>
		<descrição>   crã 6.67" 
          Câmara Traseira 12MP
        Bateria 4680mAh
          Android 11</descrição>
		 <preco>169€</preco>
		 <vídeo>https://youtu.be/h7rRlB9ytBs?si=9zHB-ZuWmwA67kee</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Smarthpone Oppo A57s 6.56" 4GB/128GB</nome>
		<imagem>imagens/oppoA57s.jpg</imagem>
		<descrição>     Carregamento SuperVooc de 33W
       Bateria de 5000mAh de Longa Duração
              Câmara Dupla de 50MP com IA
        Ecrã de 6.56" com Cores Vibrantes</descrição>
		 <preco>229€</preco>
		 <vídeo>https://youtu.be/erXJN0H5S34?si=Zl97QSJMCXPL85Zf</vídeo>
	</Produto>
	
	

	
</library>

=== FilipeVilela280/tcm23twg02/library_Laptos.xml
<?xml version="1.0"?>
<library xmlns="http://www.library.org"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.library.org library_XSD.xsd" >

	<Produto >
		<nome>Portátil Victus by HP Gaming Laptop</nome>
		<imagem>imagens/PortatilVictusbyHPGamingLaptop.jpg</imagem>
		<descrição>AMD Ryzen™ 7 7840HS 8-Core
        512 GB
         Memória RAM_16GB
        NVIDIA® GeForce RTX™ 4060 8GB GDDR6 </descrição>
		 <preco>1099€</preco>
		 <vídeo>https://youtu.be/7tymDB6ZBLs?si=p0Ru6-jOu9Uv6vTI</vídeo>
	</Produto>
	
	<Produto >
		
		<nome>Portátil Lenovo Legion 5 </nome>
		<imagem>imagens/PortatilLenovoLegion5.jpg</imagem>
		<descrição>AMD Ryzen™ 5 5600H Hexa-Core
        Memória RAM_8GB
            NVIDIA GeForce RTX 3060 6GB</descrição>
		 <preco>899€</preco>
		 <vídeo>https://youtu.be/laWGy3HLhxU?si=F_FRa9p6UZGCY5Hg</vídeo>
	</Produto>
	
	
	<Produto >
	
		<nome>Apple MacBook Pro 14.2</nome>
		<imagem>imagens/AppleMacBookPro.jpg</imagem>
		<descrição>
        M3 Pro CPU 11‑core
        GPU 14‑core
        SSD 1TB
        36GB RAM
*</descrição>
		 <preco>2999€</preco>
		 <vídeo>https://youtu.be/0pg_Y41waaE?si=hL0Q-qC9N95DnTMZ</vídeo>
	</Produto>
	
	
	<Produto >
		<nome>Portátil MSI 15.6" Cyborg 15</nome>
		<imagem>imagens/PortatilMSICyborg15.jpg</imagem>
		<descrição>ntel® Core™ i5-12450H 8-Core
      Memória RAM 16 GB
      NVIDIA GeForce® RTX 4060 8GB GDDR6
     </descrição>
		 <preco>1199€</preco>
		 <vídeo>https://youtu.be/H1PGMDA6C6A?si=4uDTDcMxKNwWlBw3</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>portátil LG gram 17Z90Q 17" WQXGA</nome>
		<imagem>imagens/ortatilLGgram17Z90QWQXGA.jpg</imagem>
		<descrição>   Intel® Core™ i5-1240P 12-Core
        Memória RAM 16 GB
       Intel® Iris® Xe Graphics </descrição>
		 <preco>1049€</preco>
		 <vídeo>https://youtu.be/j-NocnFWcAc?si=KFan_LL4QoheNTVK</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Portátil Lenovo IdeaPad Gaming 3 </nome>
		<imagem>imagens/PortatilLenovoIdeaPadGaming3.jpg</imagem>
		<descrição>  AMD Ryzen™ 5 5600H Hexa-Core
         Memória RAM 8GB
        NVIDIA GeForce RTX 3050 4GB </descrição>
		 <preco>649€</preco>
		 <vídeo>https://youtu.be/qHUDshF8Pb8?si=RtPd1bwUkLMnrKz5</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Portátil MSI Bravo 17</nome>
		<imagem>imagens/PortatilMSIBravo17.jpg</imagem>
		<descrição>
           AMD Ryzen™ 7
            Memória RAM_16GB
               NVIDIA GeForce RTX 4060 8GB </descrição>
		 <preco>1249€</preco>
		 <vídeo>https://youtu.be/NSrgJiSVApc?si=yO9YF4L7Iq3c99YC</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Portátil Asus VivoBook 15 K513</nome>
		<imagem>imagens/PortatilAsusVivoBook15K513.jpg</imagem>
		<descrição>Intel® Core™ i5-1135G7 Quad-Core
        Memória RAM_8G
       GeForce MX330 2GB GDDR5</descrição>
		 <preco>629€</preco>
		 <vídeo>https://youtu.be/O0OnkJ9tJ84?si=XwvOhDacu2c_Jf69</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Lenovo IdeaPad Duet 3 Chromebook</nome>
		<imagem>imagens/enovoIdeaPadDuet3Chromebook.jpg</imagem>
		<descrição>Qualcomm Snapdragon 7c Gen 2 
         Memória RAM_ 4G 
              Qualcomm Adreno</descrição>
		 <preco>2586€</preco>
		 <vídeo>https://youtu.be/2ge6-AtCOsY?si=DTT2k-X0Z3V5tuGx</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Portátil Asus Zenbook 15 OLED</nome>
		<imagem>imagens/PortatilAsusZenbook15OLED.jpg</imagem>
		<descrição>  AMD Ryzen™ 7 7735U 8-Core
       Memória RAM_ 16g
       AMD Radeon™ 680M
       SSD 512GB</descrição>
		 <preco>1049€</preco>
		 <vídeo>https://youtu.be/ChiEWkN54kA?si=ekqzZ79Wakk6nGW4</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Portátil OMEN by HP Gaming Laptop</nome>
		<imagem>imagens/PortatilOMENbyHPGamingLaptop16-n0009np.jpg</imagem>
		<descrição>    AMD Ryzen™ 9 6900HX 8-Core
        SSD 1 TB
          Memória RAM_32
        AMD Radeon™ RX 6650M 8GB GDDR6</descrição>
		 <preco>2190€</preco>
		 <vídeo>https://youtu.be/vBmiAYdAstY?si=i-WCQSm4z7_ZCJpX</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Portátil Lenovo ThinkPad T14 Gen 4</nome>
		<imagem>imagens/PortatilLenovoThinkPadT14Gen4.jpg</imagem>
		<descrição>    Intel® Core™ i7-1355U 10-Core
       SSD 512GB                        
           Memória RAM_ 16
           Intel® Iris® Xe Graphic</descrição>
		 <preco>2159€</preco>
		 <vídeo>https://youtu.be/ldK7Z0a6COY?si=OCZXXKdiHRyafh_Y</vídeo>
	</Produto>
	
	

	
</library>

=== FilipeVilela280/tcm23twg02/Html/library_Componentes.xml
<?xml version="1.0"?>
<library  xmlns="http://www.library.org"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.library.org library_XSD.xsd">

	<Produto >
		<nome>Memória RAM Corsair Vengeance LPX 8GB</nome>
		<imagem>imagens/MemoriaRAMCorsairVengeanceLPX8GB.jpg</imagem>
		<descrição>Capacidade: Single-Channel 8GB (8GBx1)
          Tipo: DDR4
          Velocidade: 2400MHz </descrição>
		 <preco>190€</preco>
		 <vídeo>https://youtu.be/8wbcW__ASbA?si=UqfplvVEqcIWVdwr</vídeo>
	</Produto>
	
	<Produto >
		
		<nome>Processador Intel Core i7-12700F (12ª Geração) </nome>
		<imagem>imagens/ProcessadorIntelCorei7.jpg</imagem>
		<descrição>Capacidade de sucção: 4000Pa
        Bateria: 5200 mAh
        Tempo de carregamento: Apróx. 6 horas</descrição>
		 <preco>324€</preco>
		 <vídeo>https://youtu.be/ALMsw99iK14?si=-yz6h3gJvaHiFi8z</vídeo>
	</Produto>
	
	
	<Produto >
	
		<nome>Caixa Micro-ATX Mars Gaming MC-S2 Compact</nome>
		<imagem>imagens/CaixaMicro-ATXMarsGamingMC-S2Compact.jpg</imagem>
		<descrição>  2x Ventoinhas FRGB incluídas
        Grelha frontal
        Water Cooler até 240mm*</descrição>
		 <preco>230€</preco>
		 <vídeo>https://youtu.be/fu_bG3GFFt4?si=asm5ESndBCF3yqyT</vídeo>
	</Produto>
	
	
	<Produto >
		<nome>placa Gráfica Asus GeForce RTX 4060 Ti Dual White</nome>
		<imagem>imagens/MotorGraficoNVIDIAGeForceTX4060.jpg</imagem>
		<descrição> CMotor Gráfico: NVIDIA GeForce RTX 4060 Ti
			Arquitetura: NVIDIA Ada Lovelace
			Núcleos Ray Tracing: 3ª Geração
			Núcleos Tensor: 4ª Geração </descrição>
		 <preco>447€</preco>
		 <vídeo>https://youtu.be/XfdvgoZGT_c?si=3v--bRlQaO2KuMh1</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Water Cooler CPU Corsair iCUE H170i</nome>
		<imagem>imagens/WaterCoolerCPUCorsairiCUEH170i.jpg</imagem>
		<descrição> Ecrã IPS LCD de 2,1” personalizada
        Velocidades da ventoinha PWM de até 1.700 RPM 
        Pasta térmica premium CORSAIR XTM70 pré-aplicada </descrição>
		 <preco>394€</preco>
		 <vídeo>https://youtu.be/bB514MemYqs?si=SkwnJYhbeLjnsP_V</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Memória RAM G.SKILL Trident Z5 RGB 96GB</nome>
		<imagem>imagens/MemoriaRAMGSKILLTridentZ5RGB96GB.jpg</imagem>
		<descrição>Maior estabilidade para overclock
        Compatível com Intel® XMP 3.0
        Iluminação RGB</descrição>
		 <preco>471€</preco>
		 <vídeo>https://youtu.be/p5gixfJw2ec?si=-wYImj_S4HKKIM6A</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Processador AMD Ryzen 7 7800X3D "Zen 4" 8-Core</nome>
		<imagem>imagens/ProcessadorAMDRyzen77800X3D8-Core.jpg</imagem>
		<descrição>
            O processador dominante para jogos
             tecnologia AMD 3D V-Cache
            Processador de 5nm com núcleos "Zen 4" de alto desempenho</descrição>
		 <preco>429€</preco>
		 <vídeo>https://youtu.be/wAqLqD7YhgI?si=0MRSdL3NZ7VXKVxx</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Motherboard ATX MSI MAG B550 Tomahawk</nome>
		<imagem>imagens/MotherboardATXMSIMAGB550Tomahawk.jpg</imagem>
		<descrição>Tecnologia Core Boost  
        Mystic Light
        PWM IC Digital</descrição>
		 <preco>169€</preco>
		 <vídeo>https://youtu.be/HidVddtu6Zs?si=BK-xWBp9GlZDNHN1</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Placa Gráfica Sapphire Radeon RX 7800 XT Pure 16GB</nome>
		<imagem>imagens/PlacaGraficaSapphireRadeonRX7800XTPure16GB.jpg</imagem>
		<descrição>tecnologia de chiplet
         Memória: 16GB GDDR6</descrição>
		 <preco>589€</preco>
		 <vídeo>https://youtu.be/t0AQFC9fBsY?si=XdNaXETjTrl3GYFm</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Processador AMD Ryzen 9 7950X3D "Zen 4" 16-Core</nome>
		<imagem>imagens/ProcessadorAMDRyzen97950X3D16-Core.jpg</imagem>
		<descrição> processador dominante para jogos
        Processador de 5nm com núcleos "Zen 4" de alto desempenho
        Suporte a memória DDR5 e PCIe® 5.0 em Socket AM5</descrição>
		 <preco>759€</preco>
		 <vídeo>https://youtu.be/_WihI6eqXw4?si=0GC-IeeEWklqdgX-</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Fonte de Alimentação ATX Corsair AX1600i </nome>
		<imagem>imagens/ontedeAlimentacaoATXCorsairAX1600i.jpg</imagem>
		<descrição>   Capacidade: 1600W
        Eficiência: Até 94 %
        OEM: Flextronics</descrição>
		 <preco>567€</preco>
		 <vídeo>https://youtu.be/kq2B2HKNjRY?si=UG2A-ixKfxGcaspw</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Processador Intel Core i9-13900K (13ª Geração)</nome>
		<imagem>imagens/ProcessadorIntelCorei9-13900K.jpg</imagem>
		<descrição> Mais eficiência em desempenho multitasking
         Arquitetura híbrida de desempenho melhorada
        Processador 13ª Geração Intel Core, Geração Raptor Lake</descrição>
		 <preco>669€</preco>
		 <vídeo>https://youtu.be/BYuJU5NPAhY?si=TiZ8hEHNSJzGj9Y7</vídeo>
	</Produto>
	
	

	
</library>

=== FilipeVilela280/tcm23twg02/Html/library_Descktops.xml
<?xml version="1.0"?>
<library xmlns="http://www.library.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.library.org library_XSD.xsd">

	<Produto>
		<nome>PC LENOVO IC 3 07ADA5-457</nome>
		<imagem>imagens/PCLENOVIC307ADA5-457.jpg</imagem>
		<descrição> AMD Athlon
 128 GB
  Memória RAM_ 4
 AMD Radeon Graphics </descrição>
		<preco>349€</preco>
		<vídeo>https://youtu.be/NP2Q_SnPaJc?si=vSQWQb6lVb0PhVHr</vídeo>
	</Produto>

	<Produto>

		<nome>PC LENOVO V530S-7ICR-11BM002APG</nome>
		<imagem>imagens/PCLENOVOV530S-7ICR-11BM002APG.jpg</imagem>
		<descrição>Intel Core i5  
  Memória RAM_ 8
     Intel® UHD Graphics 630</descrição>
		<preco>749€</preco>
		<vídeo>https://youtu.be/m7MK9oERU1w?si=M9WFZlXGRx-rqUrM</vídeo>
	</Produto>


	<Produto>

		<nome>PC LENOVO V530S-7ICR-11BM002MPG</nome>
		<imagem>imagens/PCLENOVOV530S-7ICR-11BM002APG.jpg</imagem>
		<descrição>Intel Core i7
 Memória RAM_ 8
 Intel® UHD Graphics 630</descrição>
		<preco>819€</preco>
		<vídeo>PC LENOVO V530S-7ICR-11BM002MPG</vídeo>
	</Produto>


	<Produto>
		<nome>Desktop Gaming Lenovo Legion T5 </nome>
		<imagem>imagens/DesktopGamingLenovoLegionT5.jpg</imagem>
		<descrição>AMD Ryzen 7 5700G Octa Core
 Memória RAM
            16 GB
    NVIDIA GeForce RTX 3070 </descrição>
		<preco>1399€</preco>
		<vídeo>https://youtu.be/c9TPrOewFKY?si=ZFl5pVRiJEkUXDP_</vídeo>
	</Produto>


	<Produto>

		<nome>MAC STUDIO APPLE M2 ULT 1TB 2023</nome>
		<imagem>imagens/MACSTUDIOAPPLEM2ULT1TB2023.jpg</imagem>
		<descrição>1 TB
        
 8 GB
        
        
Ecrã AMOLED 120Hz 
        </descrição>
		<preco>4164€</preco>
		<vídeo>https://youtu.be/LS2f-Ko0GYo?si=NhwDhlmcAdfHJdTo</vídeo>
	</Produto>


	<Produto>

		<nome>PC ASUS S500MC I3-10100</nome>
		<imagem>imagens/PCASUSS500MCI3-10100.jpg</imagem>
		<descrição>Intel Core i3
  Memória RAM_ 8</descrição>
		<preco>384€</preco>
		<vídeo>https://youtu.be/-8CghLxCVdY?si=mm6ony0NiYgCEVHU</vídeo>
	</Produto>


	<Produto>

		<nome>PC ACER ASPIRE XC-840</nome>
		<imagem>imagens/Pcacer.jpg</imagem>
		<descrição>
    Intel Celeron
     Memória RAM_ 4
         Intel UHD
    </descrição>
		<preco>129€</preco>
		<vídeo>https://youtu.be/F-0zLZz2N_E?si=P6pI06BX1pkVvRlD</vídeo>
	</Produto>


	<Produto>

		<nome>PC FUJITSU ESPRIMO D711EPC71MPT</nome>
		<imagem>imagens/PCFUJITSUESPRIMOD711EPC71MPT.jpg</imagem>
		<descrição> Intel

 Memória RAM_ 16
      </descrição>
		<preco>1259€</preco>
		<vídeo>https://youtu.be/XdjYhFzQmsY?si=qojsqLW-9XtW1xF4</vídeo>
	</Produto>


	<Produto>

		<nome>PC HP GT22-0022NP</nome>
		<imagem>imagens/PCHPGT22-0022NP.jpg</imagem>
		<descrição>  AMD Ryzen 9 
  512 GB 
      Memória RAM_ 32 
          NVIDIA GeForce RTX 3070 Ti </descrição>
		<preco>2586€</preco>
		<vídeo>https://youtu.be/eSqrq8v-QLs?si=GQQ-8bZsbwJ5SYqY</vídeo>
	</Produto>


	<Produto>

		<nome>MAC STUDIO APPLE M2 MAX 512G 2023</nome>
		<imagem>imagens/MACSTUDIOAPPLEM2MAX512G2023.jpg</imagem>
		<descrição>512 GB
Memória RAM_ 32
       
       </descrição>
		<preco>2440€</preco>
		<vídeo>https://youtu.be/ohv1BTr_MRY?si=zzf6Dfieau08KWld</vídeo>
	</Produto>


	<Produto>

		<nome>PC ACER ASPIRE XC-840 239</nome>
		<imagem>imagens/PCACERASPIREXC-840239.jpg</imagem>
		<descrição>Intel Celeron
   256 GB
  Memória RAM_ 4
     Intel UHD</descrição>
		<preco>350€</preco>
		<vídeo>https://youtu.be/4Rsr4z1OqdU?si=cimsfhq63VJ6MNi3</vídeo>
	</Produto>


	<Produto>

		<nome>Desktop HP M01-F3002NP</nome>
		<imagem>imagens/DesktopHPM01-F3002NP.jpg</imagem>
		<descrição>AMD Ryzen 5
512 GB                         
    Memória RAM_ 8
    AMD Radeon Graphics
    </descrição>
		<preco>229€</preco>
		<vídeo>https://youtu.be/iERuInc57Jg?si=j1-KllhjuV7Oayer</vídeo>
	</Produto>


</library>

=== FilipeVilela280/tcm23twg02/library_Lifestyle.xml
<?xml version="1.0"?>
<library xmlns="http://www.library.org"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.library.org library_XSD.xsd" >

	<Produto >
		<nome>Nebulizador Beurer IH</nome>
		<imagem>imagens/NebulizadorBeurerIH.jpg</imagem>
		<descrição>ecnologia de ar comprimido 
        Elevada proporção de partículas respiráveis
        Tempo de inalação curto</descrição>
		 <preco>79€</preco>
		 <vídeo>https://youtu.be/W4NOSUcDtCo?si=jUWMxKgy_Zg89lxw</vídeo>
	</Produto>
	
	<Produto >
		
		<nome>Rolos Aquecidos Remington H9100</nome>
		<imagem>imagens/AspiradorVerticalRowenta.jpg</imagem>
		<descrição>      Design de mola melhorado
        Cobertura protetora
        Estrutura compacta para armazenamento fácil</descrição>
		 <preco>83€</preco>
		 <vídeo>https://youtu.be/O6ldFBegfKA?si=pfXczKatRSozpaIh</vídeo>
	</Produto>
	
	
	<Produto >
	
		<nome>Escova Facial Rowenta LV8530F0</nome>
		<imagem>imagens/EscovaFacialRowenta.jpg</imagem>
		<descrição>   Ação 2 em 1 de limpeza e nutrição que oferece à sua pele
        Aparelho de elevada qualidade com cerdas em silicone</descrição>
		 <preco>149€</preco>
		 <vídeo>https://youtu.be/oqZVLx0BYmY?si=i4kYshc9MTapobQT</vídeo>
	</Produto>
	
	
	<Produto >
		<nome>Intercomunicador Motorola PIP1500</nome>
		<imagem>imagens/IntercomunicadorMotorola.jpg</imagem>
		<descrição> Monitorização e Transmissão gratuita de eventos 24 horas
        Tecnologia FHSS de 2.4GHz
        Câmara VGA Manual Pan / Tilt  </descrição>
		 <preco>229€</preco>
		 <vídeo>https://youtu.be/EPRabypov_U?si=vpqVQUvP3pvspug5</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Massajador de Compressão de Pernas Beurer</nome>
		<imagem>imagens/MassajadorCompressaoPernas.jpg</imagem>
		<descrição>        Intensidade da massagem contínua ajustável
        Temporizador de 10/20/30 min
        Botão de segurança STOP
       </descrição>
		 <preco>120€</preco>
		 <vídeo>https://youtu.be/Wi1QjaPt_wo?si=jyRTibEEm7BBkYZt</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Aparador Philips OneBlade Pro Face</nome>
		<imagem>imagens/AparadorPhilipsOneBlade.jpg</imagem>
		<descrição>                     Autonomia: 120 minutos
        Carregamento: Carga completa em 1 hora
        Tipo de bateria: Iões de lítio</descrição>
		 <preco>93€</preco>
		 <vídeo>https://youtu.be/jOu_i9XLtA4?si=1bnsHhsQZA3Hk5U2</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Termómetro Corporal Withings Thermo Smart Temporal Thermometer</nome>
		<imagem>imagens/TermometroCorporalWithings.jpg</imagem>
		<descrição>
            Alta precisão: Thermo tem 16 sensores
            Sincronização automática
             Medição ultra-rápida com indicador de febre codificado por cores</descrição>
		 <preco>100€</preco>
		 <vídeo>https://youtu.be/dSur1xfQOU8?si=7MwW7Qk31rX6Iyih</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Máquina de Barbear Braun Series 7</nome>
		<imagem>imagens/MaquinaBarbearBraun.jpg</imagem>
		<descrição> Máquina de barbear elétrica com adaptação de 360° 
        Bateria Li-Ion para até 3 semanas de barbear
        Inclui um centro de limpeza SmartCare e acessório EasyClick </descrição>
		 <preco>269€</preco>
		 <vídeo>https://youtu.be/81P_iXYcOv4?si=fvoYpOfwNOGdofPQ</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Balança Corporal Withings Body Scan </nome>
		<imagem>imagens/BalancaCorporalWithings.jpg</imagem>
		<descrição>Composição corporal segmentar: Monitoriza o peso
        Saúde do coração: Indicação da sua saúde cardiovascular
        Monitor de ECG Withings</descrição>
		 <preco>399€</preco>
		 <vídeo>https://youtu.be/FrtIxjGEceM?si=s1SbIUaKJirQBsUu</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Passadeira Cecotec ExtremeTrack Vibrator</nome>
		<imagem>imagens/FritadeiraAirFryerXiaomi.jpg</imagem>
		<descrição>Velocidade ajustável: de 1 km/h a 18 km/h para os mais exigentes.
        UltraFlex system
        Automatic Tilt</descrição>
		 <preco>489€</preco>
		 <vídeo>https://youtu.be/w8G-cj9JjZ4?si=QensAwCAa7ukIJxO</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Secador de Cabelo Dreame Hair Gleam AHD12A</nome>
		<imagem>imagens/SecadorCabeloDreameHair.jpg</imagem>
		<descrição>                Alta velocidade - 110.000 RPM
        Velocidade do fluxo de ar potente - 65m/s
        Corpo ultra-leve de apenas 330 grs</descrição>
		 <preco>80€</preco>
		 <vídeo>https://youtu.be/xWmXhbuHuhc?si=ROcH07P12Re9gpEm</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Escova de Dentes Elétrica Oral-B iO Série 9S</nome>
		<imagem>imagens/EscovaDentesOral-BiO.jpg</imagem>
		<descrição>     Tmicrovibrações suaves
        Visor Interativo
            Rastreio 3D com a app Oral-b</descrição>
		 <preco>199€</preco>
		 <vídeo>https://youtu.be/CoV2XQJbqlk?si=-FLR1aHdaoTLxq1u</vídeo>
	</Produto>
	
	

	
</library>

=== FilipeVilela280/tcm23twg02/Html/library_SmartHome.xml
<?xml version="1.0"?>
<library xmlns="http://www.library.org"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.library.org library_XSD.xsd">

	<Produto >
		<nome>Camara Nedis Smart Life Indoor</nome>
		<imagem>imagens/CamaraNedisSmartLifeIndoor.jpg</imagem>
		<descrição>    Fácil de ligar diretamente à sua rede Wi-Fi
        Resolução Full HD
        Deteção de movimento e som</descrição>
		 <preco>45€</preco>
		 <vídeo>https://youtu.be/4Wrl4wmGicY?si=2nvmBBaloIPtWO3r</vídeo>
	</Produto>
	
	<Produto >
		
		<nome>Detetor de Monóxido de Carbono Nedis SmartLife</nome>
		<imagem>imagens/DetetorMonoxidoCarbonoNedis.jpg</imagem>
		<descrição>     Duração da pilha até 3 anos 
         Alarme potente - oferece um alerta precoce
         Sensor fiável - com uma vida útil estimada de 10 anos</descrição>
		 <preco>52€</preco>
		 <vídeo>https://youtu.be/YrK-1APZ-vk?si=GuV9ndqxuNEj2raw</vídeo>
	</Produto>
	
	
	<Produto >
	
		<nome>Bebedouro Inteligente Para Animais Xiaomi Smart Pet</nome>
		<imagem>imagens/BebedouroInteligenteAnimaisXiaomi.jpg</imagem>
		<descrição>       Nascente de Água Circulante 
         Filtragem em 4 Fases
        Funcionamento Silencioso 
        Conexão Inteligente</descrição>
		 <preco>61€</preco>
		 <vídeo>https://youtu.be/DVdf7IIypHQ?si=z3groiQ1gaDT5yX5</vídeo>
	</Produto>
	
	
	<Produto >
		<nome>Controlador Rega Nedis SmartLife Water Control</nome>
		<imagem>imagens/3Rega.jpg</imagem>
		<descrição>Tecnologia Bluetooth Low Energy
        Configure facilmente vários horários
        Fácil de instalar: não são necessárias ferramentas</descrição>
		 <preco>32€</preco>
		 <vídeo>https://youtu.be/gQ2YQhULMXo?si=dG0EEejst4VdobvA</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Tomada Inteligente EcoFlow Smart Plug Wi-Fi  </nome>
		<imagem>imagens/TomadaInteligenteEcoFlow.jpg</imagem>
		<descrição>    Horários e temporizadores
        Controlo por voz
        Ativado para Wi-Fi e Bluetooth
        Ecrã AMOLED 120Hz
        </descrição>
		 <preco>29€</preco>
		 <vídeo>https://youtu.be/SCt8qcYgT60?si=twHYvno837TnONvM</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Sensor Portas e Janelas EZVIZ T2C </nome>
		<imagem>imagens/SensorPortasEZVIZT2C.jpg</imagem>
		<descrição>  Alertas instantâneos através da aplicação EZVIZ
        Alarme anti-violação
        Instalação com fita adesiva</descrição>
		 <preco>29€</preco>
		 <vídeo>https://youtu.be/5B1ksERdSmo?si=weVx5_90C1nqNIF0</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Candeeiro de Mesa Nedis SmartLife Mood Light Wi-Fi</nome>
		<imagem>imagens/CandeeiroMesNedisSmartLife.jpg</imagem>
		<descrição>
            Design fino, minimalista e economizador de espaço
            Plug and play: conetividade direta com o seu Wi-Fi
            Opções de iluminação reguláveis</descrição>
		 <preco>83€</preco>
		 <vídeo>https://youtu.be/5j1hZa3bw50?si=H6MPEQvjtP3Veu5C</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Vídeo Porteiro Google Nest Doorbell Wired</nome>
		<imagem>imagens/VideoPorteiroGoogleNestDoorbellWired.jpg</imagem>
		<descrição>        Câmara: sensor a cores de 8,46 mm e 3 megapixeis
        Campo de visão: 160° diagonal
        Áudio: altifalante e microfone de alta qualidade</descrição>
		 <preco>219€</preco>
		 <vídeo>https://youtu.be/N_xfwAm79iY?si=nckEIsDiEwW8nBeh</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Fechadura Inteligente EZVIZ</nome>
		<imagem>imagens/FechaduraInteligenteEZVIZ.jpg</imagem>
		<descrição>Inclui Keypad Multifuncional
        Inclui Keypad Multifuncional
        Desbloqueio sem chave via aplicativo</descrição>
		 <preco>199€</preco>
		 <vídeo>https://youtu.be/eGFl8nPnVdI?si=L_78HLDFnkGEJOJa</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Termostato Inteligente Google Nest Learning</nome>
		<imagem>imagens/FritadeiraAirFryerXiaomi.jpg</imagem>
		<descrição> Bateria (recarregável)
        LCD a cores de 4 bits
        Bluetooth de baixa energia</descrição>
		 <preco>241€</preco>
		 <vídeo>https://youtu.be/G-0KoWpi_0Y?si=bIsE0iktWsc2e6Td</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Iluminação Ambiente Nanoleaf Hexagons</nome>
		<imagem>imagens/IluminacaoNanoleafHexagons.jpg</imagem>
           <descrição> imagen Crie o seu próprio design
            Sincronize com a sua música
            15x Painéis de Formas Hexagonais</descrição>
		 <preco>299€</preco>
		 <vídeo>https://youtu.be/5hfr3nwB5MI?si=B4GZ6ewAg3UVjnxE</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Câmara de Segurança IP Ubiquiti G4 Dome 2K  </nome>
		<imagem>imagens/CamaraSegurancaIPUbiquiti.jpg</imagem>
		<descrição> Resolução de vídeo 2K 
        Ângulo de visualização ultra-amplo
            Deteções de eventos AI</descrição>
		 <preco>649€</preco>
		 <vídeo>https://youtu.be/n9NQYDCLeVs?si=USl1cIp-sA7Y-sF1</vídeo>
	</Produto>
	
	

	
</library>
