=== FilipeVilela280/tcm23twg02/Html/library_XSD.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.library.org"
    xmlns:tns="http://www.library.org"
    elementFormDefault="qualified">
   
    <element name="library">
        <complexType>
            <sequence>
                <element name="Produto" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="nome" type="string" />
                            <element name="imagem"  >
                                <simpleType>
                                    <restriction base="string">
                                        <pattern
                                            value="imagens\/[a-zA-Z0-9_-]+\.jpg"></pattern>
                                    </restriction>
                                </simpleType>
                            </element>
 
                            <element name="descrição" type="string"/>
                            <element name="preco" >
                                <simpleType>
                                    <restriction base="string">
                                        <pattern
                                            value="\d+€"></pattern>
                                    </restriction>
                                </simpleType>
                            </element>

                            
                            <element name="vídeo" type="string"/>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>

</schema>

=== FilipeVilela280/tcm23twg02/Html/library_Televisores.xml
<?xml version="1.0"?>
<library xmlns="http://www.library.org"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.library.org library_XSD.xsd" >

	<Produto >
		<nome>Televisão LG 32LQ63806LC SmartTV 32" LED FHD</nome>
		<imagem>imagens/lg32lq.jpg</imagem>
		<descrição>Painel LED com resolução HD Ready 
		 Processador α5 Gen5 AI 
		 Smart TV ThinQ™ AI com sistema operativo webOS 22</descrição>
		 <preco>289€</preco>
		 <vídeo>https://youtu.be/UifDVeuHGFc?si=2GQNtZXXI-jphvcM</vídeo>
	</Produto>
	
	<Produto >
		
		<nome>Televisão Smart TV LG Série B3 165,1cm OLED 4K UHD </nome>
		<imagem>imagens/lgserieb3.jpg</imagem>
		<descrição>Processador α7 AI 4K Gen6
		 ThinQ AI e WebOS
		Tipo de painel: OLED 4K</descrição>
		 <preco>296€</preco>
		 <vídeo>https://www.youtube.com/watch?v=sWZ8BIxbnDU</vídeo>
	</Produto>
	
	
	<Produto >
	
		<nome>Televisão Smart TV Sony Bravia Série X75WL 127cm LED 4K UHD Google TV</nome>
		<imagem>imagens/sonybraviax75wl.jpg</imagem>
		<descrição> Direct LED 
		 processador de Imagem: 4K Processor X1™
		taxa de atualização do painel: 50/60 Hz</descrição>
		 <preco>6909€</preco>
		 <vídeo>https://youtu.be/ExgxXjjHhm4?si=vyXlKxqJNXRNXh6s</vídeo>
	</Produto>
	
	
	<Produto >
		<nome>Televisão Smart TV Xiaomi Mi 4S 139,7cm LED 4K UHD Android TV</nome>
		<imagem>imagens/xiaomiMi4s.jpg</imagem>
		<descrição>PCPU: Quad Core (até 1,5 GHz)
		Ângulo de Visão: 178°(H)/178°(V)
		DTS-HD</descrição>
		 <preco>390€</preco>
		 <vídeo>https://youtu.be/u8K9bRoovpY?si=G59E9LimcrqG-uLA</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Televisão Samsung QN90A SmartTV 65" Neo QLED 4K UHD</nome>
		<imagem>imagens/samsungQN90A.jpg</imagem>
		<descrição>Motor de Imagem Processador Neo Quantum 4K 
		  Um bilhão de cores Sim
		Índice Qualidade de Imagem (PQI) 4500
		HDR (High Dynamic Range) Quantum HDR 2000 </descrição>
		 <preco>2221€</preco>
		 <vídeo>https://youtu.be/MG4g4kblvTE?si=JVHOvOTAsn1V6Ar9</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Televisão Monitor LG 24TQ510S-PZ 23.6" LED HD</nome>
		<imagem>imagens/monitorlg24t.jpg</imagem>
		<descrição>Amplo Ângulo de Visão
		Smart TV WebOS 22
		Coluna Stereo 5W </descrição>
		 <preco>159€</preco>
		 <vídeo>https://youtu.be/-INKwikqdvg?si=PB96yUv_EAFUV1BX</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Televisão Smart TV LG Série UR91 165,1cm LED 4K UHD webOS</nome>
		<imagem>imagens/LGserieur91.jpg</imagem>
		<descrição>UHD com resolução 4K
	 Processador α5 Gen6 4K AI
	Smart TV ThinQ™ AI com sistema operativo webOS 23</descrição>
		 <preco>699€</preco>
		 <vídeo>https://youtu.be/eAdy5V6UxEQ?si=9SAYyKeXKDrtR0u0</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Televisão Samsung LS03CSmartTV 55" QLED 4K UHD</nome>
		<imagem>imagens/SamsungLSS03C.jpg</imagem>
		<descrição>Moldura Personalizável com Design Moderno 
		 100% Volume de Cor com Tecnologia Quantum Dot
		 Modo Arte 
		One Connect e Ligações Invisíveis</descrição>
		 <preco>1099€</preco>
		 <vídeo>https://youtu.be/WGQmk6pOqDI?si=lS-dBwPSf3JQOole</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Televisão Sony KD-32W804 SmartTV LED HD Ready Android TV</nome>
		<imagem>imagens/sonykd-32w804.jpg</imagem>
		<descrição>levada gama dinâmica
		 BRAVIA ENGINE
		Sistema Operativo Android TV™
		 Chromecast incorporado</descrição>
		 <preco>349€</preco>
		 <vídeo>https://youtu.be/HFYfZTXVrC0?si=8k50uVeLyo9Awy2c</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Televisão Smart TV Sony Bravia XR Série A90K OLED 4K UHD</nome>
		<imagem>imagens/SONYBRAVIA.jpg</imagem>
		<descrição>OLED 4K
		  Cognitive Processor XR™ 
		Modo de latência baixa 
		Upscaling 3D Surround</descrição>
		 <preco>1649€</preco>
		 <vídeo>https://youtu.be/qc9En0fBICQ?si=ybpGnGcz8xchfSNK</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Televisão Samsung CU8505 SmartTV 50" LED 4K UHD</nome>
		<imagem>imagens/SamsungCU8505.jpg</imagem>
		<descrição> tamanho de ecrã: 50" 
		 Resolução: 3.840 x 2.160 
		Motor de imagem: Processador Crystal 4K
		HLG (Hybrid Log Gamma)</descrição>
		 <preco>479€</preco>
		 <vídeo>https://youtu.be/lNbkNRvvYtg?si=ddar1vpSWtO3oISR</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Televisão Smart TV Xiaomi P1E 55"/140cm LED 4K UHD Android TV</nome>
		<imagem>imagens/Xiaomip1e.jpg</imagem>
		<descrição>esolução: 4K Ultra HD (3840 x 2160)    
		Ângulos de visualização: 178º (H) / 178º (V)
			 Dolby Vision
		 Taxa de atualização: 60 Hz</descrição>
		 <preco>389€</preco>
		 <vídeo>https://youtu.be/7JNbVrBDfjQ?si=QhbiwgzP--YqM6HS</vídeo>
	</Produto>
	
	

	
</library>

=== FilipeVilela280/tcm23twg02/library_GrandesEletrodomesticos.xml
<?xml version="1.0"?>
<library xmlns="http://www.library.org"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.library.org library_XSD.xsd" >

	<Produto >
		<nome>Exaustor Teka DVT 98660 TBS BK</nome>
		<imagem>imagens/ExaustorTekaDV.jpg</imagem>
		<descrição> Painel de comandos Touch Control 
      Indicador digital de velocidade selecionada
      Sistema de aspiração perimetral "Contour"</descrição>
		 <preco>387€</preco>
		 <vídeo>https://youtu.be/vhu2TGHx9sQ?si=38FTBqqrL_E4ZrrI</vídeo>
	</Produto>
	
	<Produto >
		
		<nome>Placa de Indução CASO Maitre 2400</nome>
		<imagem>imagens/InducaoCASO.jpg</imagem>
		<descrição>Ecrã digital de grandes dimensões
       Particularmente rápido e potente - cerca de 2400 watts
        Temperatura ajustável com precisão de 60 a 240 °C</descrição>
		 <preco>107€</preco>
		 <vídeo>https://youtu.be/X0t87DwZoF0?si=3uIQwY3zbuALYgYp</vídeo>
	</Produto>
	
	
	<Produto >
	
		<nome>Máquina Secar Roupa Zanussi ZDH8353W 8kg</nome>
		<imagem>imagens/MaquinaSecarZanussi.jpg</imagem>
		<descrição>  Capacidade de secagem: 8 kg
        Tecnologia com bomba de calor

        Display LCD médio</descrição>
		 <preco>519€</preco>
		 <vídeo>https://youtu.be/lVJvSZG6ULU?si=CwQfPFw6pCPUk_Si</vídeo>
	</Produto>
	
	
	<Produto> <nome>Arca Vertical Zanussi ZYAN8EW0 </nome>
		<imagem>imagens/ArcaVerticalZanuss.jpg</imagem>
		<descrição>   Controlo mecânico
       Descongelação manual
       Pés ajustáveis </descrição>
		 <preco>469€</preco>
		 <vídeo>https://youtu.be/fdfXgN_84_c?si=UgdHY3s2ULENdsXF</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Máquina de Lavar Loiça LG DF325FW</nome>
		<imagem>imagens/MaquinaLavarLG.jpg</imagem>
		<descrição>Eficiência energética A++
       Eficiência de secagem A
       Consumo anual de energia 266 kWh

       Ecrã AMOLED 120Hz  </descrição>
		 <preco>539€</preco>
		 <vídeo>https://youtu.be/skqedx5Be_U?si=8XtwfY45Y2BGcGBe</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Máquina de Lavar Roupa MiniLG F8K5XN3</nome>
		<imagem>imagens/MaquinaLavarRoupaMiniLG.jpg</imagem>
		<descrição >Duas Lavagens diferentes ao mesmo tempo
     Capacidade de Lavagem 2Kg
     Motor Slim DD de 3 movimentos</descrição>
		 <preco>294€</preco>
		 <vídeo>https://youtu.be/G1BQcFCk9MQ?si=AW2hOusf9pj_7ok6</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Placa de Cozinha Indução Samsung NZ64B6058GK</nome>
		<imagem>imagens/PlacaCozinhaInducaoSamsung.jpg</imagem>
		<descrição>
           Zona Flexível Plus 
           Conectividade Wi-Fi
           Compatível com SmartThings</descrição>
		 <preco>482€</preco>
		 <vídeo>https://youtu.be/qwxBlnjFMVk?si=Cmvx3zdltptoZFOW</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Frigorífico Combinado Samsung RB33B610EBN</nome>
		<imagem>imagens/FrigorificoCombinadoSamsung.jpg</imagem>
		<descrição>  capacidade de 344L
        Tipo de refrigeração: All Around Cooling
        No Frost
       </descrição>
		 <preco>739€</preco>
		 <vídeo>https://youtu.be/IHsvHbE9Iwo?si=odlSqRfq8N6KhL_r</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome> Micro-ondas de Encastre Siemens iQ500 BE555LMS0</nome>
		<imagem>imagens/Micro-ondasEncastreSiemens.jpg</imagem>
		<descrição>O display touchSlider permite controlar as várias funções 
        Potência máxima: 900W
        úmero de níveis de potência:5</descrição>
		 <preco>359€</preco>
		 <vídeo>https://youtu.be/tfGqUiLRmzI?si=IrP0fRu2nU-Nsf8R</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Forno Elétrico de Encastre Samsung NV7B4550VAS</nome>
		<imagem>imagens/FornoEletricosamsunf.jpg</imagem>
		<descrição>     Dual Cook Flex™
           Capacidade de 76L 
         Porta Flexível </descrição>
		 <preco>603€</preco>
		 <vídeo>https://youtu.be/p5CppbDwSlI?si=hgEP8FtxZPqIk4fZ</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Máquina de Lavar Loiça de Livre Instalação LG DF455HSS</nome>
		<imagem>imagens/MaquinaLavarLoicaLG.jpg</imagem>
		<descrição> Máxima higienização com TrueSteam™ 
          Sistema de braços QuadWash™
        Design EasyRack™ Plus com 3 cestos reguláveis</descrição>
		 <preco>817€</preco>
		 <vídeo>https://youtu.be/doi_ZHSLPQ4?si=PjfguBJLOZGFgz1I</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Máquina de Lavar Samsung WW80T4040EE 8kg 1400RPM</nome>
		<imagem>imagens/maquinalavarsamsung.jpg</imagem>
		<descrição>  Consumo de Energia (100 Ciclos): 73 kWh
       Duração do ciclo Eco 40-60 (h:mm): 3:38
             Eficiência de Centrifugação: B
       lasse de emissão de ruído: A</descrição>
		 <preco>354€</preco>
		 <vídeo>https://youtu.be/EA_1x129Qq4?si=AXiFQCvOmr9oTgXo</vídeo>
	</Produto>
	
	

	
</library>

=== FilipeVilela280/tcm23twg02/library_PequenosEletrodomesticos.xml
<?xml version="1.0"?>
<library xmlns="http://www.library.org"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.library.org library_XSD.xsd">

	<Produto >
		<nome>Máquina de Café Automática CASO Café Crema</nome>
		<imagem>imagens/MaquinaCafeCASO.jpg</imagem>
		<descrição>Ecrã com operação intuitiva por sensor tátil 
        Pressão da bomba: máx. 19 bar
       Prática função de água quente para fazer chá</descrição>
		 <preco>599€</preco>
		 <vídeo>https://youtu.be/FszVZCh8fdY?si=Gkyk2Sh4dWAmd1fP</vídeo>
	</Produto>
	
	<Produto >
		
		<nome>Aspirador Vertical Rowenta Dual Force 2</nome>
		<imagem>imagens/AspiradorVerticalRowenta.jpg</imagem>
		<descrição>Tecnologia: Ciclónica  
        Sistema Bagless
        Usage: Touch-ups (2 in 1)</descrição>
		 <preco>129€</preco>
		 <vídeo>https://youtu.be/A0iLQ_jkEcc?si=QYkIrrQ-qaapNPeW</vídeo>
	</Produto>
	
	
	<Produto >
	
		<nome>Ferro Vapor Deerma Garment Steamer HS007</nome>
		<imagem>imagens/FerroVaporDeerma.jpg</imagem>
		<descrição>  Potência: 800W 
         Capacidade do depósito de agua: 100mL
        Peso: 1.1 kg</descrição>
		 <preco>190€</preco>
		 <vídeo>https://youtu.be/OYGx6IyiH38?si=pvTgIUJLiLMPV776</vídeo>
	</Produto>
	
	
	<Produto >
		<nome>Aspirador Robô iRobot Roomba i3+</nome>
		<imagem>imagens/AspiradoriRobot.jpg</imagem>
		<descrição> Esvaziamento Automático
         ligação Wi-Fi
        Limpeza completa com a tecnologia Dirt Detect™. </descrição>
		 <preco>339€</preco>
		 <vídeo>https://youtu.be/dks2MoCWGhc?si=YCAZKAqybvri3laG</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Ferro Caldeira Black Decker</nome>
		<imagem>imagens/FerroCaldeiraBlackDecker.jpg</imagem>
		<descrição>     Potência: 2200 W
       Base: Cerâmica
       Autonomia: Ilimitada horas  </descrição>
		 <preco>79€</preco>
		 <vídeo>https://youtu.be/2L80lLwRTtw?si=XOikmyXehkAtFK7o</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Liquidificadora Nutribullet NBF400DG</nome>
		<imagem>imagens/liquidificadoraNutribulletNBF400DG.jpg</imagem>
		<descrição>  Base de motor com 1200 watts
        Lâmina extratora com encaixe Easy-Twist
        Jarro de 1,8 L</descrição>
		 <preco>100€</preco>
		 <vídeo>https://youtu.be/uqYct39rGp4?si=w8xD0LtgXj_EqneV</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Purificador de Ar TCL Breeva</nome>
		<imagem>imagens/PurificadorArTCL.jpg</imagem>
		<descrição>
            O filtro de carvão ativo absorve o odor e os COV.
            Os sensores duplos monitorizam a qualidade do ar
            Modo automático para ajustar a velocidade do ventilador</descrição>
		 <preco>129€</preco>
		 <vídeo>https://youtu.be/js6j0N6YURg?si=7Io8OLCnJUR6Zl2e</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Aquecedor a Óleo DeLonghi Dragon4 TRD4</nome>
		<imagem>imagens/AquecedorOleoDeLonghi.jpg</imagem>
		<descrição>             Potência de aquecimento - Máx (W): 2000 
         Potência de aquecimento - Med (W): 1100
        Potência de aquecimento - Mín (W): 900</descrição>
		 <preco>130€</preco>
		 <vídeo>https://youtu.be/LdKZs7-yMe4?si=qu1-k--lHun8OCUP</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Máquina de Café DeLonghi Magnifica</nome>
		<imagem>imagens/MaquinaCafeDeLonghi.jpg</imagem>
		<descrição>Capacidade do depósito de grãos (g): 250 
         Capacidade do depósito de água (l): 1.8
      Capacidade do depósito para moído (n): 14</descrição>
		 <preco>390€</preco>
		 <vídeo>https://youtu.be/EvhTr-3x3mg?si=n1VtHyZRVRDrqzkB</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Fritadeira Air Fryer Xiaomi Smart Air</nome>
		<imagem>imagens/FritadeiraAirFryerXiaomi.jpg</imagem>
		<descrição> 1600W de potência
        Temperatura ajustável entre 40ºC e 200ºC
        Revestimento interior anti-aderente</descrição>
		 <preco>80€</preco>
		 <vídeo>https://youtu.be/sBSDjpWsRWk?si=1ACTRF2YTJYQlCU8</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Aspirador Robô Xiaomi Mi Robot Vacuum S10+</nome>
		<imagem>imagens/AspiradorRoboXiaomiMi.jpg</imagem>
		<descrição>Capacidade de sucção: 4000Pa
        Bateria: 5200 mAh
        Tempo de carregamento: Apróx. 6 horas</descrição>
		 <preco>400€</preco>
		 <vídeo>https://youtu.be/Dt2PjMIuJ9Q?si=EpZClMByqUqCcsQv</vídeo>
	</Produto>
	
	
	<Produto >
		
		<nome>Purificador de Ar AEG APU72571DG 7000 Pure Multi</nome>
		<imagem>imagens/PurificadorArAEG.jpg</imagem>
		<descrição>                Tecnologia 4 etapas de filtragem
        Sensores Humidade,
            Painel de controlo Tátil</descrição>
		 <preco>230€</preco>
		 <vídeo>https://youtu.be/O90i9cRAvn0?si=oFZrj86jT0D_HC_A</vídeo>
	</Produto>
	
	

	
</library>
